language: java
sudo: false
install: true

addons:
  sonarqube:
    token: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  - mvn clean package
  - mvn cobertura:cobertura

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
